<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="3" skipped="0" tests="4" time="0.767" timestamp="2022-07-06T21:05:40.038792" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.entity.Test.test_patient.test_patient" name="test_access_session" file="FYP\entity\Test\test_patient.py" line="32" time="0.024"><failure message="AttributeError: __enter__">client = &lt;test_patient.test_patient testMethod=test_access_session&gt;

    def test_access_session(client):
&gt;       with client:
E       AttributeError: __enter__

FYP\entity\Test\test_patient.py:34: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.entity.Test.test_patient.test_patient" name="test_login" file="FYP\entity\Test\test_patient.py" line="13" time="0.011"><failure message="NameError: name 'username' is not defined">self = &lt;test_patient.test_patient testMethod=test_login&gt;

    def test_login(self):
       with app.test_client() as client:
           client.post('/LoginController', data=dict(username='s', password='s'))
           with client.session_transaction() as session:
&gt;              self.assertTrue(username)
E              NameError: name 'username' is not defined

FYP\entity\Test\test_patient.py:18: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.entity.Test.test_patient.test_patient" name="test_pass_correct" file="FYP\entity\Test\test_patient.py" line="19" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.entity.Test.test_patient.test_patient" name="test_pass_incorrect" file="FYP\entity\Test\test_patient.py" line="27" time="0.004"><failure message="AssertionError: False is not true">self = &lt;test_patient.test_patient testMethod=test_pass_incorrect&gt;

    def test_pass_incorrect(self):
        tester = app.test_client(self)
        response = tester.post('/LoginController', data=dict(username = 'wenling', password='password'))
&gt;       self.assertTrue(b'password' in response.data)
E       AssertionError: False is not true

FYP\entity\Test\test_patient.py:31: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>