<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.576" timestamp="2022-07-06T17:34:59.817315" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_Patient.test_patient" name="test_Login" file="FYP\Test\test_Patient.py" line="29" time="0.016"><failure message="KeyError: 'username'">self = &lt;test_Patient.test_patient testMethod=test_Login&gt;

    def test_Login(self):
        #result = 5+6
        #self.assertEqual(result, 11)
        #with self.client:
        #    response = self.client.post('login', { username: 'James', password: '007' })
            # success
        #    assertEquals(user.username, 'James')
        with app.test_client() as client:
            client.post('/LoginController', data=dict(username='s', password='s'))
            with client.session_transaction() as session:
                #self.assertTrue(session['logged_in'])
&gt;               self.assertEqual(session['username'], 'wenling')

FYP\Test\test_Patient.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;SecureCookieSession {}&gt;, key = 'username'

    def __getitem__(self, key: str) -&gt; t.Any:
        self.accessed = True
&gt;       return super().__getitem__(key)
E       KeyError: 'username'

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\flask\sessions.py:79: KeyError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>