<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="4" skipped="0" tests="5" time="2.621" timestamp="2022-07-07T17:13:30.823193" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_patient.test_patient" name="test_index" file="FYP\Test\test_patient.py" line="49" time="0.041"><failure message="ModuleNotFoundError: No module named 'validateLogin'">self = &lt;test_patient.test_patient testMethod=test_index&gt;

    def test_index(self):
&gt;       with patch("validateLogin.session", dict()) as session:

FYP\Test\test_patient.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\mock.py:1389: in __enter__
    self.target = self.getter()
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\mock.py:1564: in &lt;lambda&gt;
    getter = lambda: _importer(target)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

target = 'validateLogin'

    def _importer(target):
        components = target.split('.')
        import_path = components.pop(0)
&gt;       thing = __import__(import_path)
E       ModuleNotFoundError: No module named 'validateLogin'

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\mock.py:1236: ModuleNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_listing_all_users" file="FYP\Test\test_patient.py" line="46" time="0.017"><failure message="NameError: name 'username' is not defined">self = &lt;test_patient.test_patient testMethod=test_listing_all_users&gt;

    def test_listing_all_users(self):
&gt;       self.assertTrue(self.login(username, password).status_code == 200)
E       NameError: name 'username' is not defined

FYP\Test\test_patient.py:48: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_login" file="FYP\Test\test_patient.py" line="36" time="0.053"><failure message="KeyError: 'logged_in'">self = &lt;test_patient.test_patient testMethod=test_login&gt;

    def test_login(self):
       with app.test_client() as client:
           #client.post('/Patient_Main', data=dict(username='s', password='s'))
           client.get('/Patient_Main', data=dict(username='s', password='s'))
           with client.session_transaction() as sess:
&gt;              self.assertTrue(sess['logged_in'] == True)

FYP\Test\test_patient.py:42: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;SecureCookieSession {}&gt;, key = 'logged_in'

    def __getitem__(self, key: str) -&gt; t.Any:
        self.accessed = True
&gt;       return super().__getitem__(key)
E       KeyError: 'logged_in'

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\flask\sessions.py:79: KeyError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_pass_correct" file="FYP\Test\test_patient.py" line="59" time="0.023"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_pass_incorrect" file="FYP\Test\test_patient.py" line="67" time="0.015"><failure message="AssertionError: False is not true">self = &lt;test_patient.test_patient testMethod=test_pass_incorrect&gt;

    def test_pass_incorrect(self):
        tester = app.test_client(self)
        response = tester.post('/Patient_Main', data=dict(username = 'wenling', password='password'))
&gt;       self.assertTrue(b'wenling, password' in response.data)
E       AssertionError: False is not true

FYP\Test\test_patient.py:71: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>