<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.534" timestamp="2022-07-05T12:35:59.300153" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_Patient.test_patient" name="test_Login" file="FYP\Test\test_Patient.py" line="6" time="0.016"><failure message="AttributeError: 'test_patient' object has no attribute 'username'">self = &lt;test_Patient.test_patient testMethod=test_Login&gt;

    def test_Login(self):
&gt;       self.assertTrue(self.username == 'wenling')
E       AttributeError: 'test_patient' object has no attribute 'username'

FYP\Test\test_Patient.py:8: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>