<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.805" timestamp="2022-07-06T17:36:26.267315" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_Patient.test_patient" name="test_Login" file="FYP\Test\test_Patient.py" line="29" time="0.018"><failure message="NameError: name 'username' is not defined">self = &lt;test_Patient.test_patient testMethod=test_Login&gt;

    def test_Login(self):
        #result = 5+6
        #self.assertEqual(result, 11)
        #with self.client:
        #    response = self.client.post('login', { username: 'James', password: '007' })
            # success
        #    assertEquals(user.username, 'James')
        with app.test_client() as client:
            client.post('/LoginController', data=dict(username='s', password='s'))
            with client.session_transaction() as session:
                #self.assertTrue(session['logged_in'])
&gt;               self.assertEqual(username, 'wenling')
E               NameError: name 'username' is not defined

FYP\Test\test_Patient.py:41: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>