<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.814" timestamp="2022-07-05T18:55:01.736611" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_Patient.test_patient" name="test_Login" file="FYP\Test\test_Patient.py" line="22" time="0.017"><failure message="AssertionError: 11 != 12">self = &lt;test_Patient.test_patient testMethod=test_Login&gt;

    def test_Login(self):
        result = 5+6
&gt;       self.assertEqual(result, 12)
E       AssertionError: 11 != 12

FYP\Test\test_Patient.py:25: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>