<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.105" timestamp="2022-07-05T11:44:06.726869" hostname="LAPTOP-9RU984SS"><testcase classname="FYP.FYP.FYP.Test.test_Patient.test_patient" name="test_Login" file="FYP\FYP\FYP\Test\test_Patient.py" line="7" time="0.006"><failure message="AttributeError: 'test_patient' object has no attribute 'username'">self = &lt;test_Patient.test_patient testMethod=test_Login&gt;

    def test_Login(self):
&gt;       self.assertTrue(self.username == 'wenling')
E       AttributeError: 'test_patient' object has no attribute 'username'

FYP\FYP\FYP\Test\test_Patient.py:9: AttributeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>